services:
  subweb:
    image: subhanafz/subweb:latest
    volumes:
    - ./instance:/app/instance
    - ./static/download_files:/app/static/download_files
    expose:
    - "8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app
    restart: "always"
    env_file:
      - .env
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - subweb
    restart: "always"
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
    depends_on:
      - subweb
    command: certonly --webroot -w /var/www/certbot --force-renewal --email subhanafzal125@gmail.com -d subhan.work -d analytics.subhan.work --agree-tos
  plausible:
    image: ghcr.io/plausible/community-edition:latest
    container_name: plausible
    restart: always
    expose:
      - "5000"
  #server-pico_server:
  #  image: server-pico_server
  #  expose:
  #    - "5000"
  #    - "6000:6000"
  #  ports:
  #  depends_on:
  #  restart: "always"
  #    - subweb
  #  command: python server.py
    

