services:
  subweb:
    image: subhanafz/subweb:latest
    volumes:
    - ./instance:/app/instance
    - ./static/download_files:/app/static/download_files
    expose:
    - "8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app
    restart: "always"
    env_file:
      - .env
    networks:
      - public_webserver
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./certbot/conf/:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - subweb
    restart: "always"
    networks:
      - public_webserver
  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    depends_on:
      - subweb
    command: >
      certonly
      --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
      -d subhan.work
      --expand
      --non-interactive
      --agree-tos
      --email subhanafzal125@gmail.com
    networks:
      - public_webserver
  
networks:
  public_webserver:
    external: true