services:
  subweb:
    image: subhanafz/subweb:latest
    volumes:
    - ./app/instance:/app/instance
    - ./app/static/download_files:/app/static/download_files
    expose:
    - "8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app
    restart: "always"
    env_file:
      - .env
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - subweb
    restart: "always"
