services:
  subweb:
    image: subhanafz/subweb:latest
    volumes:
    - ./instance:/app/instance
    - ./static/download_files:/app/static/download_files
    expose:
    - "8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app
    restart: "always"
    env_file:
      - .env
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./certbot/conf/:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - subweb
    restart: "always"
  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    depends_on:
      - subweb
    command: >
      certonly
      --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
      -d subhan.work -d analytics.subhan.work
      --non-interactive
      --agree-tos
      --email subhanafzal125@gmail.com
  plausible:
    image: ghcr.io/plausible/community-edition:latest
    container_name: plausible
    restart: always
    environment:
      - BASE_URL=https://analytics.subhan.work
    expose:
      - "5000"
  #server-pico_server:
  #  image: server-pico_server
  #  expose:
  #    - "5000"
  #    - "6000:6000"
  #  ports:
  #  depends_on:
  #  restart: "always"
  #    - subweb
  #  command: python server.py
    

