name: Build, Push Docker image and Deploy via Tailscale to web server.

on:
    push:
        branches: ["master"]
        paths:
            - "app/**"
            - "nginx/**"



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Images & Push to Docker Hub
        run: |
            docker buildx build --platform linux/amd64,linux/arm64 -t subhanafz/subweb:latest --push ./app/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Tailscale & Connect to Tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
      - name: Deploy to Web Server
        run: |
            ssh -o "StrictHostKeyChecking=no" ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
                cd ~/subweb
                git pull
                docker compose -f docker-compose.prod.yml down
                docker compose -f docker-compose.prod.yml pull 
                docker compose -f docker-compose.prod.yml up -d
            "